name: FastAPI CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install pytest fastapi uvicorn httpx
      - name: Run tests
        run: pytest tests/

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/fastapi-demo:latest
            ghcr.io/${{ github.repository_owner }}/fastapi-demo:${{ github.sha }}
          labels: |
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}

  update-k8s-manifests:
    needs: build-and-push
    runs-on: ubuntu-latest
    permissions:
      contents: write  # FIXED: Added write permission
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # FIXED: Explicit token for write access
          fetch-depth: 0  # FIXED: Get full history for pushing
      - name: Update image in Kubernetes manifest
        run: |
          sed -i "s|REPLACE_OWNER|${{ github.repository_owner }}|g" kubernetes/deployment.yaml
      - name: Commit updated manifests
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add kubernetes/deployment.yaml
          git commit -m "Update image owner in deployment manifest [skip ci]" || echo "No changes to commit"
          git push
