# .github/workflows/ci-cd-cloudrun.yml
name: FastAPI Cloud Run Deployment (Smoke Test + Rollback)

on:
  push:
    branches: ["main"]

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GHCR_TOKEN }}

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy fastapi-demo \
            --image=europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/fastapi-repo/fastapi-demo:latest \
            --region=europe-west1 \
            --platform=managed \
            --allow-unauthenticated \
            --update-env-vars=DEPLOY_ENV=production \
            --timeout=20s

      - name: Smoke test new deployment
        run: |
          SERVICE_URL=$(gcloud run services describe fastapi-demo --region=europe-west1 --format='value(status.url)')
          echo "Testing service at $SERVICE_URL"
          sleep 10
          curl -f "$SERVICE_URL/healthz" || (echo "Smoke test failed" && exit 1)

      - name: Rollback on failure
        if: failure()
        run: |
          PREV_REV=$(gcloud run revisions list \
            --service fastapi-demo \
            --region=europe-west1 \
            --sort-by="~createTime" \
            --format="value(metadata.name)" | sed -n 2p)
          echo "Rolling back to $PREV_REV"
          gcloud run services update-traffic fastapi-demo \
            --region=europe-west1 \
            --to-revisions $PREV_REV=100
